<?php
/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Industry;
use Faker\Generator as Faker;

$industries = [
    'Accommodation',
    'Administrative and Support Services',
    'Agriculture, Forestry, Fishing and Hunting',
    'Air Transportation',
    'Amusement, Gambling, and Recreation Industries',
    'Apparel Manufacturing',
    'Arts, Entertainment, and Recreation',
    'Broadcasting',
    'Chemical Manufacturing',
    'Clothing and Clothing Accessories Stores',
    'Computer and Electronic Product Manufacturing',
    'Construction',
    'Crop Production',
    'Data Processing, Hosting, and Related Services',
    'Educational Services',
    'Electronics and Appliance Stores',
    'Finance and Insurance',
    'Food Manufacturing',
    'Food and Beverage Stores',
    'Forestry and Logging',
    'Furniture and Home Furnishings Stores',
    'Gasoline Stations',
    'General Merchandise Stores',
    'Health Care and Social Assistance',
    'Health and Personal Care Stores',
    'Heavy and Civil Engineering Construction',
    'Hospitals',
    'Insurance Carriers and Related Activities',
    'Internet Publishing and Broadcasting',
    'Leisure and Hospitality',
    'Machinery Manufacturing',
    'Manufacturing',
    'Merchant Wholesalers',
    'Miscellaneous Manufacturing',
    'Miscellaneous Store Retailers',
    'Motion Picture and Sound Recording Industries',
    'Motor Vehicle and Parts Dealers',
    'Museums, Historical Sites, and Similar Institutions',
    'Natural Resources and Mining',
    'Nursing and Residential Care Facilities',
    'Paper Manufacturing',
    'Performing Arts, Spectator Sports, and Related Industries',
    'Personal and Laundry Services',
    'Petroleum and Coal Products Manufacturing',
    'Pipeline Transportation',
    'Plastics and Rubber Products Manufacturing',
    'Postal Service',
    'Primary Metal Manufacturing',
    'Printing and Related Support Activities',
    'Publishing Industries',
    'Rail Transportation',
    'Real Estate and Rental and Leasing',
    'Religious, Grantmaking, Civic, Professional, and Similar Organizations',
    'Repair and Maintenance',
    'Scenic and Sightseeing Transportation',
    'Securities, Commodity Contracts, and Other Financial Investments and Related Activities',
    'Specialty Trade Contractors',
    'Sporting Goods, Hobby, Book, and Music Stores',
    'Telecommunications',
    'Textile Product Mills',
    'Trade, Transportation, and Utilities',
    'Transit and Ground Passenger Transportation',
    'Transportation and Warehousing',
    'Truck Transportation',
    'Utilities',
    'Warehousing and Storage',
    'Waste Management and Remediation Services',
    'Water Transportation',
    'Wholesale Electronic Markets and Agents and Brokers',
    'Wholesale Trade',
    'Wood Product Manufacturing',
];

$factory->define(Industry::class, function (Faker $faker) use ($industries) {
    return [
        'name' => $faker->unique()->randomElement($industries),
    ];
});
